from django.urls import path
from student import views
# from .views import GetStudentQuizScoreAPIView,FacultyQuizListAPIView,UpdateQuizStatusAPIView,UpdateStudentCountAPIView,RefreshTokenAPIView,QuizOptionManageAPIView,QuizManageAPIView,QuizQuestionsManageAPIView,AllFacultyListAPIView,QuizScoreAPIView,SubmitAnswerAPIView,QuizQuestionsAPIView,QuizListAPIView,StudentListAPIView,StudentCreateAPIView,CourseListAPIView,CourseCreateAPIView,SearchStudentListAPIView,LoginStudentAPIView,GenrateTokenAPIView,StudentProfileAPIView,StudentListPageAPIView,ProfilePictureUploadView,AssignmentCreateAPIView,StudentAssignmentList,ForgotPasswordAPIView,ResetPasswordAPIView,AssignmentSubmitAPIView,ValidatePasswordTokenAPIView,UpdateStudentStatusAPIView

urlpatterns = [
    path("student/",views.StudentListAPIView.as_view()),
    path("student/page/",views.StudentListPageAPIView.as_view()),
    path("student/create/",views.StudentCreateAPIView.as_view()),
    path("student/update/<int:id>/", views.StudentCreateAPIView.as_view()),
    path("student/profile_image/",views.ProfilePictureUploadView.as_view()),
    path("student/<int:student_id>/toggle-status/",views.UpdateStudentStatusAPIView.as_view()),
    path("student/<int:student_id>/count/",views.UpdateStudentCountAPIView.as_view()),
    path("student/search/",views.SearchStudentListAPIView.as_view()),
    path("student/profile/<int:student_id>/score/",views.GetStudentQuizScoreAPIView.as_view()),
    path("course/",views.CourseListAPIView.as_view()),
    path("course/create/",views.CourseCreateAPIView.as_view()),
    path("course/update/<int:id>/",views.CourseCreateAPIView.as_view()),
    path("course/delete/<int:id>/",views.CourseCreateAPIView.as_view()),
    path("login/",views.LoginStudentAPIView.as_view()),
    path("login/password/update/",views.LoginStudentAPIView.as_view()),
    path("login/token/",views.GenrateTokenAPIView.as_view()),
    path("token/refresh/", views.RefreshTokenAPIView.as_view()),
    path("login/google/", views.GoogleLoginAPIView.as_view()),
    path("profile/",views.StudentProfileAPIView.as_view()),
    path("assignment/", views.AssignmentCreateAPIView.as_view()),
    path("assignment/update/<int:id>/", views.AssignmentCreateAPIView.as_view()),
    path("assignment/submit/", views.AssignmentSubmitAPIView.as_view()),
    path("student/assignment/my/<int:id>", views.StudentAssignmentList.as_view()),
    path("forgot-password/",views.ForgotPasswordAPIView.as_view()),
    path("reset-password/",views.ResetPasswordAPIView.as_view()),
    path("reset-password/validate-token/",views.ValidatePasswordTokenAPIView.as_view()),
    path("quizzes/",views.QuizListAPIView.as_view()),
    path("faculty/quizzes/",views.FacultyQuizListAPIView.as_view()),
    path("quizzes/<int:quiz_id>/questions/",views.QuizQuestionsAPIView.as_view()),
    path("answers/",views.SubmitAnswerAPIView.as_view()),
    path("quizzes/<int:quiz_id>/score/",views.QuizScoreAPIView.as_view()),
    path("faculty-detail/",views.AllFacultyListAPIView.as_view()),
    path("faculty/quizzes/<int:quiz_id>/toggle-status/",views.UpdateQuizStatusAPIView.as_view()),
    path("faculty/quizzes/<int:quiz_id>/questions/",views.QuizQuestionsManageAPIView.as_view()),
    path("faculty/question/create/",views.QuizQuestionsManageAPIView.as_view()),
    path("faculty/option/create/",views.QuizOptionManageAPIView.as_view()),
    path("faculty/quiz/create/",views.QuizManageAPIView.as_view()),
    path("faculty/attendance/create/",views.TodayAttendance.as_view()),
    path("student/attendance/",views.StudentAttendanceAPIView.as_view()),
    path("student/attendance/history/",views.StudentFullAttendanceAPIView.as_view()),
]

